Update README.md
Build fails with Node 14 because Object.hasOwn was introduced in Node 16.9.0:

```
[webpack-cli] TypeError: Object.hasOwn is not a function
    at getBlockJsonScriptFields (.../node_modules/@wordpress/scripts/utils/block-json.js:28:15)
    at .../node_modules/@wordpress/scripts/utils/config.js:253:9
```