Remove redundant code causing unit test failure
The unit tests on mobile are currently failing due to the following error:

> TypeError: Cannot read property 'color' of undefined

This commit seeks to resolve that failure by removing the offending, redundant code.