style: Address lint warning
Disable unused variable warning as the `$request` parameter must be
referenced to satisfy inherited class requirements.

```
Fatal error: Declaration of WP_REST_Block_Editor_Assets_Controller::get_items_permissions_check() must be compatible with WP_REST_Controller::get_items_permissions_check($request) in /var/www/html/wp-content/plugins/gutenberg/lib/experimental/class-wp-rest-block-editor-assets-controller.php on line 144
```