Fix the missed onChange attribute
CategorySelect requires the onChange attribute for avoiding throwing an error message that says: "Uncaught TypeError: onChange is not a function".
Related to the issue https://github.com/WordPress/gutenberg/issues/24667.