[RNMobile] Upgrade Gradle to `8.2.1` and AGP to `8.1.0` (#52872)
* Build: Move android related gradle properties to its own group for aztec

* Deps: Extract agp version to settings build gradle for aztec

* Deps: Extract publish to s3 version to settings build gradle for aztec

* Deps: Add versions groups to root build gradle for aztec

* Deps: Extract androidx legacy version to root build gradle for aztec

* Deps: Extract androidx gridlayout version to root build gradle for aztec

* Deps: Extract androidx cardview version to root build gradle for aztec

* Deps: Extract androidx appcompat version to root build gradle for aztec

* Deps: Extract androidx recyclerview version to root bld gradle for aztec

* Deps: Extract junit version to root build gradle for aztec

FYI: You will notice an additional 'aztec' related 'junit' version. This
is because the node modules are using an older version of JUnit, the
'4.12', that is, comparing to the newer '4.13' version that the 'aztec'
modules are using. As such, and in order to avoid behavior changes, two
such version were extracted to the root 'build.gradle' file with an
accompanying TODO for the future.

* Build: Upgrade gradle to 8.1.1 for aztec (1/2)

Release Notes: https://docs.gradle.org/8.1.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.1.1
--distribution-type=all

------------------------------------------------------------------------

FYI: You will notice that the associated 'gradle-wrapper.jar', 'gradlew'
and 'gradlew.bat' files are not updated. This is because of the breaking
changes that this upgrade introduces, including the 'AGP' upgrade and
its associated breaking changes (namespace, build option, etc). As such,
this Gradle upgrade command is only half done.

PS: When all the breaking changes are resolved, this Gradle command will
be issued again, which should fully complete this upgrade.

* Build: Upgrade agp to 8.0.2 for aztec

Release Notes: https://developer.android.com/build/releases/
gradle-plugin#agp-8-0-2

* Build: Move package from android manifest to build files for aztec

This is an AGP version '8.0' breaking change that requires 'namespace'
in module-level build scripts, see build failure below:

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project
 '@wordpress_react-native-aztec'.
> Failed to notify project evaluation listener.
   > Could not create an instance of type
    com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
      > Namespace not specified. Please specify a namespace in the
       module's build.gradle file like so:

        android {
            namespace 'com.example.namespace'
        }

        If the package attribute is specified in the source
         AndroidManifest.xml, it can be migrated automatically to the
         namespace value in the build.gradle file using the AGP Upgrade
         Assistant; please refer to https://developer.android.com/
         studio/build/agp-upgrade-assistant for more information.
   > Could not get unknown property 'bundleReleaseAar' for object of
    type org.gradle.api.publish.maven.internal.publication
    .DefaultMavenPublication.

------------------------------------------------------------------------

Explanation: "You must set the namespace in the module-level
'build.gradle.kts' file, rather than the manifest file."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#

* Build: Upgrade gradle to 8.1.1 for aztec (2/2)

Release Notes: https://docs.gradle.org/8.1.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.1.1
--distribution-type=all

------------------------------------------------------------------------

As per the previous d85ad7bda1a594de7d890d1d241561b3490e12df commit and
its description, this change is a follow-up upgrade, which fully
completes this Gradle upgrade.

* Build: Migrate dsl properties from lint options to lint for aztec

FYI: This was suggested automatically using the AGP upgrade assistant.

* Build: Upgrade gradle to 8.2.1 for aztec

Release Notes: https://docs.gradle.org/8.2.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.2.1
--distribution-type=all

* Build: Move android related gradle prop. to its own group for bridge

* Deps: Extract agp version to settings build gradle for bridge

* Deps: Extract publish to s3 version to settings build gradle for bridge

* Deps: Extract facebook fresco react native related version for bridge

* Deps: Extract google material version to root build gradle for bridge

* Deps: Extract wordpress utils version to root build gradle for bridge

* Deps: Extract junit version to root build gradle for bridge

* Build: Upgrade gradle to 8.1.1 for bridge (1/2)

Release Notes: https://docs.gradle.org/8.1.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.1.1
--distribution-type=all

------------------------------------------------------------------------

FYI: You will notice that the associated 'gradle-wrapper.jar', 'gradlew'
and 'gradlew.bat' files are not updated. This is because of the breaking
changes that this upgrade introduces, including the 'AGP' upgrade and
its associated breaking changes (namespace, build option, etc). As such,
this Gradle upgrade command is only half done.

PS: When all the breaking changes are resolved, this Gradle command will
be issued again, which should fully complete this upgrade.

* Build: Upgrade agp to 8.0.2 for bridge

Release Notes: https://developer.android.com/build/releases/
gradle-plugin#agp-8-0-2

* Build: Move package from android manifest to build files for bridge

This is an AGP version '8.0' breaking change that requires 'namespace'
in module-level build scripts, see build failure below:

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project
 '@wordpress_react-native-bridge'.
> Failed to notify project evaluation listener.
   > Could not create an instance of type
    com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
      > Namespace not specified. Please specify a namespace in the
       module's build.gradle file like so:

        android {
            namespace 'com.example.namespace'
        }

        If the package attribute is specified in the source
         AndroidManifest.xml, it can be migrated automatically to the
         namespace value in the build.gradle file using the AGP Upgrade
         Assistant; please refer to https://developer.android.com/
         studio/build/agp-upgrade-assistant for more information.
   > Could not get unknown property 'bundleReleaseAar' for object of
    type org.gradle.api.publish.maven.internal.publication
    .DefaultMavenPublication.

------------------------------------------------------------------------

Explanation: "You must set the namespace in the module-level
'build.gradle.kts' file, rather than the manifest file."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#

* Build: Enable build config build feature for bridge

This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-bridge'.
> Failed to notify project evaluation listener.
   > com.android.builder.errors.EvalIssueException: defaultConfig
    contains custom BuildConfig fields, but the feature is disabled.
   > Could not get unknown property 'bundleReleaseAar' for object of
    type org.gradle.api.publish.maven.internal.publication
    .DefaultMavenPublication.

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 doesn't generate
'BuildConfig' by default. You need to specify this option using the DSL
in the projects where you need it."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes

* Build: Upgrade gradle to 8.1.1 for bridge (2/2)

Release Notes: https://docs.gradle.org/8.1.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.1.1
--distribution-type=all

------------------------------------------------------------------------

As per the previous 5ff4e6e6f754b33bd0f41634230fa27e4b8a8c26 commit and
its description, this change is a follow-up upgrade, which fully
completes this Gradle upgrade

* Build: Migrate dsl properties from lint options to lint for bridge

FYI: This was suggested automatically using the AGP upgrade assistant.

* Build: Upgrade gradle to 8.2.1 for bridge

Release Notes: https://docs.gradle.org/8.2.1/release-notes.html
Command: ./gradlew wrapper --gradle-version=8.2.1
--distribution-type=all

* Build: Upgrade gradle to 8.2.1 for editor

* Build: Upgrade agp to 8.0.2 for editor

* Build: Move package from android manifest to build files for editor

* Build: Enable build config build feature for editor

* Patch `react-native-gradle` package

* Include correct `react-native-aztec` project in bridge

* Use newer version of React Native Gradle plugin

* Make `else` statement one-line format in editor's `settings.gradle`

* Remove aztec project inclusion when publishing bridge binaries

* Use Java 17 in Android E2E tests

* Update publish-to-s3 Gradle plugin to 0.8.0

* Revert removing package from AndroidManifest

Revert removing package from AndroidManifest

* Add inline comment to remind updating package name

This comment will avoid forgetting about updating the package name in all places needed.

* Add `.java-version` file to use Java 17

* Bump Android Gradle Plugin to `8.1.0`

* Remove `react-native-gradle` patch

* Update `react-native-editor` changelog

* Remove TODO inline comment in `build.gradle`

---------

Co-authored-by: Petros Paraskevopoulos <petros.paraskevopoulos@automattic.com>