Prevent a console and block error on input[type=email]
When this is at the top of a block,
on first addding the block,
there is a block and JS error:
DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.

at placeCaretAtHorizontalEdge (https://path/to/wp-content/plugins/gutenberg/build/dom/index.js?ver=cbf62a0bae5cfd2eeff038ee115edc0a:390:32)

This looks to be because
HTMLInputElement only has a
selectionStart property
for 'text/number-containing or elements'
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement