Add safe nav op for accessing `length` for `document` in `addFreeForm()` as in some scenarios, `document` can be `undefined`
In some hard-to-reproduce (possibly edgy) scenarios, the `document` variable in the Index module for the `block-serialiazation-parser` package can be `undefined`. This is causing the following error in some WP instances/themes that support widgets + block widgets:

```
TypeError: Cannot read properties of undefined (reading 'length')
```

In: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-serialization-default-parser/src/index.js#L441

Unfortunately, I don't know how to consistently reproduce the issue, and this fix, while suitable for now, probably does not fix the root issue. More investigation is needed.