Update react-native-bridge to build an AAR to publish on Bintray and use in WordPress Android (#28216)
* Remove illegal '/' character from RN Android project name

* Add Bintray Gradle plugin to React Native Android bridge

* Add "fat" AAR Gradle plugin to React Native Android bridge

This will allow adding Aztec to the Gutenberg AAR to allow clients to
fallback to it.

* Configure Aztec import in RN Android bridge source or fat AAR build

Notice the addition of a white color resource. This was required by the
fat AAR generation.

Without it, the task would fail as follows:

```
> Task :reBundleAarRelease
[fat-aar]target: /path/to/repo/packages/react-native-bridge/android/build/outputs/aar/@wordpress_react-native-bridge-release.aar

> Task :verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /path/to/repo/packages/react-native-bridge/android/build/intermediates/res/merged/release/drawable/ic_check_24px.xml:6: error: resource color/white (aka org.wordpress.mobile.ReactNativeGutenbergBridge:color/white) not found.
  ...
```

* Add configuration for Gradle to publish RN Android bridge AAR to Bintray

* Add block-support folder from mobile-gutenberg to RN Android bridge AAR

* Add unsupported blocks folder from mobile-gutenberg to RN Android bridge AAR

* Disable including Hermes in the RN Bridge AAR – It doesn't work

* Switch Bintray org from @mokagio's to @wordpress-mobile's

Time to go official

* Track `npm install` updates to the package-lock.json

This is as a result of the this CI failure:
https://github.com/WordPress/gutenberg/pull/28216/checks?check_run_id=1710376166